pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo "${GIT_URL}"
            }
        }
        stage('Test') { 
            steps {
                echo "${GIT_URL_1}"
            }
        }
        stage('Deploy') { 
            steps {
                echo "${GIT_URL_2}" 
            }
        }
    }
}
